/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/Button.vue')['default']
    BaseSelect: typeof import('./src/components/base/Select.vue')['default']
    BaseSlider: typeof import('./src/components/base/Slider.vue')['default']
    BaseSwitch: typeof import('./src/components/base/Switch.vue')['default']
    BaseToast: typeof import('./src/components/base/Toast/Index.vue')['default']
  }
}
