/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/base/Button.vue')['default']
    Index: typeof import('./src/components/base/Modal/Index.vue')['default']
    Input: typeof import('./src/components/base/Input.vue')['default']
    Select: typeof import('./src/components/base/Select.vue')['default']
    Slider: typeof import('./src/components/base/Slider.vue')['default']
    Switch: typeof import('./src/components/base/Switch.vue')['default']
  }
}
