/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppModal: typeof import('./src/components/AppModal.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Dialog: typeof import('./src/components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./src/components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./src/components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./src/components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./src/components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./src/components/ui/dialog/DialogHeader.vue')['default']
    DialogOverlay: typeof import('./src/components/ui/dialog/DialogOverlay.vue')['default']
    DialogScrollContent: typeof import('./src/components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./src/components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./src/components/ui/dialog/DialogTrigger.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Select: typeof import('./src/components/ui/select/Select.vue')['default']
    SelectContent: typeof import('./src/components/ui/select/SelectContent.vue')['default']
    SelectGroup: typeof import('./src/components/ui/select/SelectGroup.vue')['default']
    SelectItem: typeof import('./src/components/ui/select/SelectItem.vue')['default']
    SelectItemText: typeof import('./src/components/ui/select/SelectItemText.vue')['default']
    SelectLabel: typeof import('./src/components/ui/select/SelectLabel.vue')['default']
    SelectScrollDownButton: typeof import('./src/components/ui/select/SelectScrollDownButton.vue')['default']
    SelectScrollUpButton: typeof import('./src/components/ui/select/SelectScrollUpButton.vue')['default']
    SelectSeparator: typeof import('./src/components/ui/select/SelectSeparator.vue')['default']
    SelectTrigger: typeof import('./src/components/ui/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./src/components/ui/select/SelectValue.vue')['default']
    ShadcnButton: typeof import('@components/ui')['Button']
    ShadcnInput: typeof import('@components/ui')['Input']
    ShadcnSelect: typeof import('@components/ui')['Select']
    ShadcnSelectContent: typeof import('@components/ui')['SelectContent']
    ShadcnSelectItem: typeof import('@components/ui')['SelectItem']
    ShadcnSelectTrigger: typeof import('@components/ui')['SelectTrigger']
    ShadcnSelectValue: typeof import('@components/ui')['SelectValue']
    ShadcnSlider: typeof import('@components/ui')['Slider']
    ShadcnSwitch: typeof import('@components/ui')['Switch']
    ShadcnToaster: typeof import('@components/ui')['Toaster']
    Slider: typeof import('./src/components/ui/slider/Slider.vue')['default']
    Sonner: typeof import('./src/components/ui/sonner/Sonner.vue')['default']
    Switch: typeof import('./src/components/ui/switch/Switch.vue')['default']
  }
}
