import fs from 'fs'
import path from 'path'

const uiDir = path.resolve('src/components/ui')
const outputFile = path.resolve(uiDir, 'index.ts')

function getDirs(dir: string) {
	return fs
		.readdirSync(dir, { withFileTypes: true })
		.filter((d) => d.isDirectory())
		.map((d) => d.name)
}

function normalizeSlotTagsInVueFiles(dir: string) {
	const entries = fs.readdirSync(dir, { withFileTypes: true })

	for (const entry of entries) {
		const fullPath = path.join(dir, entry.name)
		if (entry.isDirectory()) {
			normalizeSlotTagsInVueFiles(fullPath)
			continue
		}
		if (!entry.name.endsWith('.vue')) continue

		const original = fs.readFileSync(fullPath, 'utf-8')
		const next = original.replace(/<slot\b([^>]*)\/>/g, '<slot$1></slot>')
		if (original !== next) {
			fs.writeFileSync(fullPath, next)
		}
	}
}

function extractExportLines(content: string) {
	return content
		.split('\n')
		.map((l) => l.trim())
		.filter((l) => l.startsWith('export'))
}

const dirs = getDirs(uiDir)

const importMap = new Map<string, Set<string>>()
const exportSet = new Set<string>()

for (const dir of dirs) {
	const file = path.join(uiDir, dir, 'index.ts')
	if (!fs.existsSync(file)) continue
	const content = fs.readFileSync(file, 'utf-8')
	const lines = extractExportLines(content)
	if (!lines.length) continue
	const names: string[] = []
	for (const line of lines) {
		// export { A, B }
		const match = line.match(/export\s*{\s*([^}]+)\s*}/)
		if (match) {
			match[1]
				.split(',')
				.map((s) => s.trim().split(' as ').pop()?.trim())
				.forEach((n) => n && names.push(n))
		}
		// export { default as X }
		const defaultMatch = line.match(/export\s*{\s*default\s+as\s+([A-Za-z0-9_]+)\s*}/)
		if (defaultMatch) {
			names.push(defaultMatch[1])
		}
	}
	if (!names.length) continue
	importMap.set(dir, new Set(names))
	names.forEach((n) => exportSet.add(n))
}

let output = '/* @generated by scripts/shadcn.ts */\n\n'
// imports
for (const [dir, names] of importMap.entries()) {
	output += `import { ${[...names].join(', ')} } from '@components/ui/${dir}'\n`
}
output += `\nexport { ${[...exportSet].join(', ')} }\n`
fs.writeFileSync(outputFile, output)
normalizeSlotTagsInVueFiles(uiDir)

console.log('✅ ShadcnUI index generated (optimized)')
