/* @generated by scripts/shadcn.ts */

import { Button } from '@components/ui/button'
import {
	Dialog,
	DialogClose,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogOverlay,
	DialogScrollContent,
	DialogTitle,
	DialogTrigger,
} from '@components/ui/dialog'
import { Input } from '@components/ui/input'
import {
	Select,
	SelectContent,
	SelectGroup,
	SelectItem,
	SelectItemText,
	SelectLabel,
	SelectScrollDownButton,
	SelectScrollUpButton,
	SelectSeparator,
	SelectTrigger,
	SelectValue,
} from '@components/ui/select'
import { Slider } from '@components/ui/slider'
import { Toaster } from '@components/ui/sonner'
import { Switch } from '@components/ui/switch'

export {
	Button,
	Dialog,
	DialogClose,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogOverlay,
	DialogScrollContent,
	DialogTitle,
	DialogTrigger,
	Input,
	Select,
	SelectContent,
	SelectGroup,
	SelectItem,
	SelectItemText,
	SelectLabel,
	SelectScrollDownButton,
	SelectScrollUpButton,
	SelectSeparator,
	SelectTrigger,
	SelectValue,
	Slider,
	Toaster,
	Switch,
}
